export const DEFAULT_STENO_DOUBT_VIDEOS = [
  {
    _id: "default-1",
    title: "How to Increase Steno Speed from 60 to 80 WPM",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    thumbnailUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop&q=80",
    description: "Learn proven shorthand speed building exercises and outline daily practice routines.",
    order: 1,
    isActive: true,
  },
  {
    _id: "default-2",
    title: "Legal Passage Shorthand Outlines & Phrases",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    thumbnailUrl: "https://images.unsplash.com/photo-1450133064473-71024230f91b?w=800&auto=format&fit=crop&q=80",
    description: "Master High Court and District Court Legal Dictation terminology and shorthand symbols.",
    order: 2,
    isActive: true,
  },
  {
    _id: "default-3",
    title: "Common Mistakes in Steno Exam Evaluation",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    thumbnailUrl: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&auto=format&fit=crop&q=80",
    description: "Detailed analysis of full mistakes, half mistakes, punctuation, and capitalization rules.",
    order: 3,
    isActive: true,
  },
  {
    _id: "default-4",
    title: "Editorial Passage Fluctuations & Speed Management",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    thumbnailUrl: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&auto=format&fit=crop&q=80",
    description: "How to handle sudden speed fluctuations and voice variations during live dictation.",
    order: 4,
    isActive: true,
  },
  {
    _id: "default-5",
    title: "UPSSSC & SSC Steno Exam Typing Rules Explained",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    thumbnailUrl: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=800&auto=format&fit=crop&q=80",
    description: "Step-by-step breakdown of backspace rules, font layouts, and mistake calculation criteria.",
    order: 5,
    isActive: true,
  },
  {
    _id: "default-6",
    title: "How to Read Difficult Shorthand Notes Fast",
    videoUrl: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    thumbnailUrl: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&auto=format&fit=crop&q=80",
    description: "Techniques for instant note transcription without getting stuck on ambiguous outlines.",
    order: 6,
    isActive: true,
  },
];
